name: Generate Release Build
on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Set Version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Packaging
        run: zip -r mira-$VERSION.zip dist/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secret.GITHUB_TOKEN }}"
          prerelease: false
          files: mira-$VERSION.zip
